### ISSUE TITLE
Referencia a ruta inexistente

### ISSUE THREAD

**Issue by Devidence7** [vpec/unizar-vv-catmdedit#1]
El repositorio por defecto para la creación de registros de metadatos, descrito
en el fichero «catmdedit/repository/sources/metadata.rdf», apunta a una ruta inexistente
(«E:\workspacesEclipse\workspace\catmdeditOpenSource\CatMDEditOpenSource\
repository\metadata»)

**Comment by vpec** [comment]
Se trata de un defecto antiguo ya corregido.

**Comment by Devidence7** [comment]
Se trata de un defecto antiguo ya corregido.
