### ISSUE TITLE
Menú Ayuda. No se puede acceder al menú usuario.

### ISSUE THREAD

**Issue by Devidence7** [vpec/unizar-vv-catmdedit#10]
**Describe the bug**
No se puede acceder al manual de usuario, en algunos sistemas operativos.

**To Reproduce**
1. Comprobar que funciona la ayuda. 
2. Comprobar que se accede al Manual de Usuario correspondiente a la última versión de la herramienta 

**Expected behavior**
- Acceso al manual actualizado.

**Desktop (please complete the following information):**
 - OS: CentOs, Ubuntu.

**Precondiciones/acciones previas**
Lanzar CatMDEdit

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta «invalid» o «wontfix».
