### ISSUE TITLE
Imposible visualización HTML para Dublin Core en CentOS

### ISSUE THREAD

**Issue by IsaacValdivia** [vpec/unizar-vv-catmdedit#11]
**Describe the bug**
No es posible visualizar con HTML metadatos de estándar Dublin Core en CentOS

**To Reproduce**
Abrir metadato en CentOS, seleccionar HTML

**Expected behavior**
Visualización exitosa (no vacía).

**Desktop (please complete the following information):**
CentOS

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta «invalid» o «wontfix».
