### ISSUE TITLE
Bug de visualización "Acerca de" Texto borroso.

### ISSUE THREAD

**Issue by Devidence7** [vpec/unizar-vv-catmdedit#13]
**Describe the bug**
En el apartado de "Acerca de" hay texto difícil de leer en la pantalla 1920 x 1080.

**To Reproduce**
1. Comprobar que funciona la ayuda.
2. Hacer clic en "Acerca de"

**Expected behavior**
- Acceso al manual actualizado y al "Acerca de" de la versión

**Screenshots**

**Precondiciones/acciones previas**
Lanzar CatMDEdit.

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta «invalid» o «wontfix».
