### ISSUE TITLE
Imposible visualización de metadatos ISO19115 e ISO19119 en algunos formatos en CentOS

### ISSUE THREAD

**Issue by IsaacValdivia** [vpec/unizar-vv-catmdedit#15]
**Describe the bug**
No es posible visualizar metadatos ISO19115 e ISO19119 en formatos diferentes al HTML (resumen de metadato) o HTML (migra)

**To Reproduce**
Doble click en el metadato de dicho estándar y probar diferentes visores

**Expected behavior**
Visualización no vacía

**Desktop (please complete the following information):**
CentOS
 
/cc @vpec @OriginalDevidence

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta «invalid» o «wontfix».
