### ISSUE TITLE
Extracción de metadatos de datos (ISO19115) de forma automática

### ISSUE THREAD

**Issue by vpec** [vpec/unizar-vv-catmdedit#16]
**Describe the bug**
CentOS: no rellena automáticamente algunos .jpg y .shp. Ubuntu no permite insertar metadatos con ruta a fichero.

**To Reproduce**
Crear un nuevo metadato ISO19115, seleccionar la ruta donde se almacena y extraer metadatos del fichero.

**Expected behavior**
Metadato generado con todos los campos resultantes de la extracción automática (diferentes según el tipo de dato).

**Desktop (please complete the following information):**
 - OS: CentOS, Ubuntu

**Additional context**
Acciones previas: Lanzar CatMDEdit y disponer de un dato por cada formato "extraible" 

/cc @OriginalDevidence

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta «invalid» o «wontfix».
