### ISSUE TITLE
Tiempo de instalación en CentOS demasiado elevado.

### ISSUE THREAD

**Issue by Devidence7** [vpec/unizar-vv-catmdedit#2]
**Describe the bug**
En CentOs (disco en red) el tiempo de instalación es muy elevado.

**To Reproduce**
1. Ejecutar el instalador de la aplicación por primera vez. 
2. Seguir las instrucciones de la ventana.

**Expected behavior**
Aplicación correctamente instalada en el entorno elegido.

**Desktop (please complete the following information):**
 - OS: CentOS
 - Version 1.0

**Additional context**
Es un bug de la categoría de instalación.
Para reproducirlo, hacer previamente:
Descargar el instalador de la aplicación

**Comment by Devidence7** [comment]
cc/ @vpec @IsaacValdivia

**Comment by miguel-latre** [comment]
Al cerrarlo, podríais haber añadido también la etiqueta «wontfix», puesto que no vais a corregirlo.
