### ISSUE TITLE
Fallo en la compatibilidad entre versiones

### ISSUE THREAD

**Issue by vpec** [vpec/unizar-vv-catmdedit#3]
**Describe the bug**
En Ubuntu y CentOS no consigue terminar el proceso de conversión de metadatos, además de crear múltiples ventanas redundantes (presentes en posteriores ejecuciones de la aplicación).

**To Reproduce**
Ejecutar la aplicación por primera vez. Seguir las instrucciones de la ventana de advertencia para transformar los metadatos antiguos a la nueva versión.

**Expected behavior**
los mds antiguos han sido transformados correctamente y que se pueden editar

**Desktop (please complete the following information):**
 - OS: CentOS, Ubuntu

**Acciones previas**
Lanzar CatMDEdit, habiendo copiado antes en el repositorio de metadatos (repository/metadata) algunos metadatos de versiones de CatMDEdit anteriores a la 4.5

/cc @OriginalDevidence

**Comment by miguel-latre** [comment]
En el enunciado de la práctica se pedía que cerrarais los defectos.
Al cerrarlos, asignad la etiqueta _«duplicate»_, _«invalid»_ o _«wontfix»_ que estiméis más adecuada. En el contexto de la realización de la práctica, podéis considerar que una incidencia consiste en un defecto inválido cuándo no estéis de acuerdo con la definición del defecto que se haya hecho y que es _«wontfix»_ en el resto de los casos, ya que no vais a corregirlos.
