### ISSUE TITLE
Exportación metadatos a formato Dublin Core HTML

### ISSUE THREAD

**Issue by IsaacValdivia** [vpec/unizar-vv-catmdedit#4]
**Describe the bug**
Exportación de metadatos a formato Dublin Core HTML (en cualquier idioma)

**To Reproduce**
Realizar exportación a formato específico

**Expected behavior**
Exportación correcta

**Desktop (please complete the following information):**
CentOS

/cc @vpec @OriginalDevidence

**Comment by miguel-latre** [comment]
Como en #3, cerradlo añadiendo una etiqueta _«invalid»_ o _«wontfix»_.

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta «invalid» o «wontfix».
