### ISSUE TITLE
Exportación a formato Excel ISO

### ISSUE THREAD

**Issue by IsaacValdivia** [vpec/unizar-vv-catmdedit#5]
**Describe the bug**
Exportación de metadatos al formato Excel ISO

**To Reproduce**
Exportación a formatos concretos

**Expected behavior**
Exportación correcta

**Desktop (please complete the following information):**
Ubuntu, CentOS

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta «invalid» o «wontfix». La descripción es un poco vaga.
