### ISSUE TITLE
Creación de repositorio

### ISSUE THREAD

**Issue by vpec** [vpec/unizar-vv-catmdedit#6]
**Describe the bug**
En Ubuntu no permite la creación de un nuevo repositorio.

**To Reproduce**
Crear  repositorio de recursos.

**Expected behavior**
Repositorio de metadatos creado.

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**
Acciones previas: Lanzar CatMDEdit

/cc @OriginalDevidence

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta «invalid» o «wontfix».
