### ISSUE TITLE
Etiquetas, textos y tooltips en varios idiomas es incorrecto.

### ISSUE THREAD

**Issue by Devidence7** [vpec/unizar-vv-catmdedit#7]
**Describe the bug**
Hay idiomas que no están completamente traducidos, el checo está en inglés. También partes del programa en su versión en español están en inglés.

**To Reproduce**
1. Navegar por los menús y ventanas de la herramienta, visualizar las etiquetas de la aplicación, incluyendo los textos que definen cada elemento de metadatos, ejemplos, etc. 
2. Prestar especial atención a etiquetas de diálogos que se abren solo a petición del usuario. 
3. Pasar el puntero por encima de los elementos de metadatos del árbol. 
4. Comprobar en varios idiomas.

**Expected behavior**
- Etiquetas existentes. 
- Definiciones y ejemplos completos
- Tooltips completos

**Desktop (please complete the following information):**
 - OS: Windows, CentOs y Ubuntu
 - Version 1.0

**Additional context**
Precondiciones/acciones previas:
Lanzar CatMDEdit

**Comment by Devidence7** [comment]
cc/ @vpec

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta «invalid» o «wontfix».
