### ISSUE TITLE
Creación de colecciones

### ISSUE THREAD

**Issue by vpec** [vpec/unizar-vv-catmdedit#8]
**Describe the bug**
El tiempo de creación es largo. No muestra un mensaje de confirmación.

**To Reproduce**
Crear un repositorio de colección automáticamente a partir de una plantilla de metadatos y de un patrón espacial proporcionado.

**Expected behavior**
Repositorio de una colección de metadatos creado.

**Desktop:**
 - OS: Ubuntu

**Additional context**
Acciones previas:
Lanzar CatMDEdit. Es necesario tener al menos una plantilla de metadatos creada

/cc @IsaacValdivia

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta «invalid» o «wontfix».
