### ISSUE TITLE
Imposible visualización de metadatos fgdc en algunos formatos

### ISSUE THREAD

**Issue by IsaacValdivia** [vpec/unizar-vv-catmdedit#9]
**Describe the bug**
Imposible visualizar datos de estándar FGDC en formatos no HTML (fgdc es) o HTML (fgdc en).

**To Reproduce**
Doble click en el metadato de estándar fgdc, selección de visualización.

**Expected behavior**
Visualización del contenido (no vacío).

**Desktop (please complete the following information):**
CentOS

/cc @vpec @OriginalDevidence

**Comment by miguel-latre** [comment]
Cerradlo añadiendo una etiqueta «invalid» o «wontfix».
